package com.pashe.app.auth

import android.app.Activity
import android.content.Context
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.Firebase
import com.google.firebase.FirebaseException
import com.google.firebase.auth.FirebaseUser
import com.google.firebase.auth.GoogleAuthProvider
import com.google.firebase.auth.PhoneAuthCredential
import com.google.firebase.auth.PhoneAuthOptions
import com.google.firebase.auth.PhoneAuthProvider
import com.google.firebase.auth.auth
import kotlinx.coroutines.tasks.await
import java.util.concurrent.TimeUnit

class AuthManager {
    private val auth get() = Firebase.auth

    val currentUser: FirebaseUser? get() = auth.currentUser

    /** A child account; parent phones only ever hold an anonymous user. */
    val isChildSignedIn: Boolean get() = currentUser?.isAnonymous == false

    sealed interface PhoneEvent {
        data class CodeSent(val verificationId: String, val token: PhoneAuthProvider.ForceResendingToken) : PhoneEvent
        data class AutoVerified(val credential: PhoneAuthCredential) : PhoneEvent
        data class Failed(val message: String) : PhoneEvent
    }

    fun startPhoneVerification(
        activity: Activity,
        phoneNumber: String,
        resendToken: PhoneAuthProvider.ForceResendingToken? = null,
        onEvent: (PhoneEvent) -> Unit,
    ) {
        val callbacks = object : PhoneAuthProvider.OnVerificationStateChangedCallbacks() {
            override fun onVerificationCompleted(credential: PhoneAuthCredential) =
                onEvent(PhoneEvent.AutoVerified(credential))

            override fun onVerificationFailed(e: FirebaseException) =
                onEvent(PhoneEvent.Failed(e.localizedMessage ?: e.javaClass.simpleName))

            override fun onCodeSent(verificationId: String, token: PhoneAuthProvider.ForceResendingToken) =
                onEvent(PhoneEvent.CodeSent(verificationId, token))
        }
        val options = PhoneAuthOptions.newBuilder(auth)
            .setPhoneNumber(phoneNumber)
            .setTimeout(60L, TimeUnit.SECONDS)
            .setActivity(activity)
            .setCallbacks(callbacks)
            .apply { resendToken?.let { setForceResendingToken(it) } }
            .build()
        PhoneAuthProvider.verifyPhoneNumber(options)
    }

    suspend fun signInWithPhoneCode(verificationId: String, code: String): FirebaseUser =
        signInWithPhoneCredential(PhoneAuthProvider.getCredential(verificationId, code))

    suspend fun signInWithPhoneCredential(credential: PhoneAuthCredential): FirebaseUser =
        auth.signInWithCredential(credential).await().user!!

    /** Google sign-in through Credential Manager; needs the Web client ID from google-services.json. */
    suspend fun signInWithGoogle(activity: Activity): FirebaseUser {
        val option = GetGoogleIdOption.Builder()
            .setFilterByAuthorizedAccounts(false)
            .setServerClientId(webClientId(activity))
            .build()
        val response = CredentialManager.create(activity)
            .getCredential(activity, GetCredentialRequest.Builder().addCredentialOption(option).build())
        val credential = response.credential
        require(credential is CustomCredential && credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL) {
            "Unexpected credential type"
        }
        val idToken = GoogleIdTokenCredential.createFrom(credential.data).idToken
        return auth.signInWithCredential(GoogleAuthProvider.getCredential(idToken, null)).await().user!!
    }

    fun signOut() = auth.signOut()

    /** Generated by the google-services plugin; looked up by name so builds without it still compile. */
    private fun webClientId(context: Context): String {
        val id = context.resources.getIdentifier("default_web_client_id", "string", context.packageName)
        check(id != 0) { "default_web_client_id missing: add google-services.json with Google sign-in enabled" }
        return context.getString(id)
    }
}
